In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
#----------------------------------------------------------------------#
# Execution time difference between simple loop and vector operations
#----------------------------------------------------------------------#
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
        
print("Vectorized ver: "+str(1000*(toc-tic))+"ms")

c = 0

tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print("For loop: "+ str(1000*(toc-tic))+"ms")

Vectorized ver: 0.6742477416992188ms
For loop: 843.0938720703125ms


In [7]:
#----------------------------------------------------------------------#
#  Broaadcasting
#----------------------------------------------------------------------#
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
# print(A)
cal = A.sum(axis = 0)
# print(cal)
percentage = 100*A/(cal.reshape(1,4))

print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
